//! Decoder for NEXRAD Level 3 (RPG) radar products.
//!
//! Level 3 has no existing Rust decoder as of 2026; this crate fills that gap. It decodes the
//! product container — WMO text header strip, 18-byte Message Header Block, 102-byte Product
//! Description Block, zlib-compressed body — and the graphic Product Symbology Block packets
//! that carry storm-cell attributes: packet 15 (Storm ID), 19 (Hail / HDA), 20 (Mesocyclone/
//! MDA). The tabular alphanumeric block is captured as text for interrogation.
//!
//! Verified against goldens generated by MetPy's `Level3File` (see `tests/`). Layout follows
//! NOAA ICD 2620001 (RPG to Class 1 User).

use std::io::Read;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("message too short: need {need} bytes at {what}, have {have}")]
    Short {
        what: &'static str,
        need: usize,
        have: usize,
    },
    #[error("bad product description block (divider {0}, expected -1)")]
    BadPdb(i16),
}

type Result<T> = std::result::Result<T, Error>;

/// A tracked storm cell (symbology packet 15, "Storm ID").
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct StormCell {
    /// Two-character cell id, e.g. "A2".
    pub id: String,
    /// Position east / north of the radar, in km.
    pub x_km: f32,
    pub y_km: f32,
}

/// A hail symbol (symbology packet 19, "HDA").
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct Hail {
    pub x_km: f32,
    pub y_km: f32,
    /// Probability of hail (%), probability of severe hail (%).
    pub poh: i16,
    pub posh: i16,
    /// Maximum estimated hail size, in units of 1/4 inch (per ICD).
    pub max_size: u16,
}

/// A mesocyclone / MDA point feature (symbology packet 20).
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct Meso {
    pub x_km: f32,
    pub y_km: f32,
    pub kind: String,
}

/// One radial of a Digital Radial Data Array (packet 16): an angular wedge of range-bin levels.
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct Radial {
    /// Start azimuth (degrees, meteorological — 0 = north, clockwise).
    pub start_deg: f32,
    /// Angular width of the wedge (degrees).
    pub delta_deg: f32,
    /// One `u8` data level per range bin (bin 0 = `first_bin` range index).
    pub levels: Vec<u8>,
}

/// A Digital Radial Data Array (packet code 16): a polar grid of `u8` data levels, decoded to
/// physical units through the product's threshold table (DVL, EET, etc.).
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct RadialArray {
    /// Range index of the first bin (bins before this are off the near edge).
    pub first_bin: u16,
    /// Number of range bins per radial.
    pub nbins: u16,
    pub radials: Vec<Radial>,
}

/// Source clocks from the Product Description Block, in UTC Unix seconds.
///
/// These are radar/RPG clocks, never receipt or download times. Invalid day/second encodings
/// remain unavailable independently; the valid neighboring clock is still retained.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct ProductTimes {
    /// Volume start, or surveillance elevation start for supplemental elevation products.
    /// Multi-elevation products can use the lowest contributing surveillance elevation start.
    /// Unavailable for product 75, whose first clock denotes generation instead of acquisition.
    pub data_start_unix: Option<i64>,
    /// RPG product generation. Products 134/135 use `volume_end_unix` instead.
    pub generation_unix: Option<i64>,
    /// End of the contributing volume, supplied in place of generation for DVL/EET (134/135).
    pub volume_end_unix: Option<i64>,
}

/// A decoded Level 3 product.
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct Level3Product {
    /// Product code (58 = Storm Tracking, 59 = Hail Index, 141 = Mesocyclone, …).
    pub code: i16,
    /// Radar latitude / longitude (degrees) and height (feet), from the PDB.
    pub lat: f32,
    pub lon: f32,
    pub height_ft: i16,
    pub times: ProductTimes,
    pub cells: Vec<StormCell>,
    pub hail: Vec<Hail>,
    pub meso: Vec<Meso>,
    /// Past-position track polylines (symbology packet 23, SCIT), each a list of (x_km, y_km)
    /// points east/north of the radar. Not cell-id tagged; associate by endpoint proximity.
    pub past_tracks: Vec<Vec<(f32, f32)>>,
    /// The tabular alphanumeric block text, if present (storm attributes table).
    pub tabular: Option<String>,
    /// The graphic alphanumeric block text, if present (per-cell STORM ID / DBZM HGT lines).
    pub graphic: Option<String>,
    /// Printable-text extraction over the whole message. Standalone-tabular products (Storm
    /// Structure, Hail) don't always populate `tabular`/`graphic` at the declared offsets, so this
    /// full-message dump is the reliable source for the tolerant, line-based table parsers.
    pub raw_text: Option<String>,
    /// Digital Radial Data Array (packet 16), for gridded products like DVL / Echo Tops.
    pub radial: Option<RadialArray>,
    /// The 16 product-dependent threshold halfwords (PDB HW31-46), decoded per product.
    pub thresholds: [i16; 16],
    /// Elevation angle in degrees for elevation-based products (the halfword just ahead of the
    /// thresholds), or `None` for volume products that have no single tilt.
    pub elevation_deg: Option<f32>,
}

/// Decode a Level 3 product from raw file bytes (WMO header + optional zlib body).
pub fn decode(raw: &[u8]) -> Result<Level3Product> {
    let body = strip_wmo(raw);
    let decompressed = zlib_all(body);
    // The decompressed body carries a second WMO abbreviated heading before the message
    // header block (mirrors MetPy stripping the WMO header again post-decompression).
    let msg = strip_wmo(decompressed.as_deref().unwrap_or(body));

    // Offsets in the PDB are half-words from the start of the message header.
    let mut r = Reader::new(msg);
    r.skip("message header block", 18)?; // MHB: code/date/time/len/src/dest/nblocks

    let pdb_start = r.pos;
    let divider = r.i16("pdb divider")?;
    if divider != -1 {
        return Err(Error::BadPdb(divider));
    }
    let lat = r.i32("lat")? as f32 / 1000.0;
    let lon = r.i32("lon")? as f32 / 1000.0;
    let height_ft = r.i16("height")?;
    let code = r.i16("prod_code")?;
    // ICD 2620001, PDB global halfwords 21..26 (relative bytes 22..34). Day 1 is
    // 1970-01-01; seconds are since UTC midnight. Notes 4/5 qualify the clock roles.
    r.pos = pdb_start + 22;
    let start_day = r.i16("data start day")?;
    let start_seconds = r.u32("data start seconds")?;
    let output_day = r.i16("product output day")?;
    let output_seconds = r.u32("product output seconds")?;
    let output = source_time(output_day, output_seconds);
    let volume_product = matches!(code, 134 | 135);
    let times = ProductTimes {
        data_start_unix: (code != 75)
            .then(|| source_time(start_day, start_seconds))
            .flatten(),
        generation_unix: (!volume_product).then_some(output).flatten(),
        volume_end_unix: volume_product.then_some(output).flatten(),
    };
    // Elevation angle (tenths of a degree) sits in the product-dependent halfword immediately
    // ahead of the threshold table; 0 means "not an elevation product".
    r.pos = pdb_start + 40;
    let elevation_deg = match r.i16("elevation") {
        Ok(t) if t != 0 => Some(t as f32 / 10.0),
        _ => None,
    };
    // Product-dependent thresholds: PDB halfwords 31-46 (16 i16) at pdb_start+42.
    let mut thresholds = [0i16; 16];
    r.pos = pdb_start + 42;
    for t in thresholds.iter_mut() {
        *t = r.i16("threshold")?;
    }
    // The three block offsets sit at the PDB tail (bytes 90..102 of the 102-byte PDB).
    r.pos = pdb_start + 90;
    let sym_off = r.u32("sym_off")? as usize;
    let graph_off = r.u32("graph_off")? as usize;
    let tab_off = r.u32("tab_off")? as usize;

    let mut cells = Vec::new();
    let mut hail = Vec::new();
    let mut meso = Vec::new();
    let mut past_tracks = Vec::new();
    let mut radial = None;
    if sym_off != 0 {
        // High-resolution digital products (DVL, EET, …) BZIP2-compress the symbology block in
        // place; decompress it first, else parse it directly. A truncated/empty symbology block
        // (e.g. tabular-only products like Storm Structure) must not abort decoding.
        let sym_bytes = &msg[(sym_off * 2).min(msg.len())..];
        if sym_bytes.starts_with(b"BZh") {
            if let Some(dec) = bunzip(sym_bytes) {
                let _ = parse_symbology(
                    &dec,
                    0,
                    &mut cells,
                    &mut hail,
                    &mut meso,
                    &mut past_tracks,
                    &mut radial,
                );
            }
        } else {
            let _ = parse_symbology(
                msg,
                sym_off * 2,
                &mut cells,
                &mut hail,
                &mut meso,
                &mut past_tracks,
                &mut radial,
            );
        }
    }
    let tabular = if tab_off != 0 {
        parse_text_block(msg, tab_off * 2, msg.len())
    } else {
        None
    };
    // The graphic block precedes the tabular one; bound its extraction so runs don't bleed across.
    let graphic = if graph_off != 0 {
        let end = if tab_off > graph_off {
            tab_off * 2
        } else {
            msg.len()
        };
        parse_text_block(msg, graph_off * 2, end.min(msg.len()))
    } else {
        None
    };

    let raw_text = parse_text_block(msg, 0, msg.len());

    Ok(Level3Product {
        code,
        lat,
        lon,
        height_ft,
        times,
        cells,
        hail,
        meso,
        past_tracks,
        tabular,
        graphic,
        raw_text,
        radial,
        thresholds,
        elevation_deg,
    })
}

fn source_time(day: i16, seconds: u32) -> Option<i64> {
    (day >= 1 && seconds < 86_400).then(|| (i64::from(day) - 1) * 86_400 + i64::from(seconds))
}

/// Walk the Product Symbology Block's layers, decoding storm-cell packets (15/19/20) and
/// skipping the rest by their declared length.
fn parse_symbology(
    msg: &[u8],
    off: usize,
    cells: &mut Vec<StormCell>,
    hail: &mut Vec<Hail>,
    meso: &mut Vec<Meso>,
    past_tracks: &mut Vec<Vec<(f32, f32)>>,
    radial: &mut Option<RadialArray>,
) -> Result<()> {
    let mut r = Reader::at(msg, off);
    let _divider = r.i16("sym divider")?;
    let _block_id = r.i16("sym block_id")?;
    let _block_len = r.u32("sym block_len")?;
    let nlayers = r.i16("sym nlayers")?.max(0);

    for _ in 0..nlayers {
        let _ldiv = r.i16("layer divider")?;
        let layer_len = r.u32("layer len")? as usize;
        let layer_end = (r.pos + layer_len).min(msg.len());
        while r.pos + 4 <= layer_end {
            let code = r.u16("packet code")?;
            // Packet 16 (Digital Radial Data Array) has NO length halfword after the code — the
            // next halfword is the index of the first range bin. Branch before reading a length.
            if code == 16 {
                *radial = parse_digital_radial(&mut r, layer_end).ok();
                r.pos = layer_end; // one radial-array packet per layer
                break;
            }
            let num_bytes = r.u16("packet len")? as usize;
            let data_start = r.pos;
            let data_end = (data_start + num_bytes).min(layer_end);
            match code {
                15 => {
                    // Storm ID: [x i16, y i16, id 2 chars] * n.
                    while r.pos + 6 <= data_end {
                        let x = r.i16("stormid x")? as f32 * 0.25;
                        let y = r.i16("stormid y")? as f32 * 0.25;
                        let id = r.ascii(2);
                        cells.push(StormCell {
                            id,
                            x_km: x,
                            y_km: y,
                        });
                    }
                }
                19 => {
                    // HDA hail: [x, y, POH, POSH, max size] * n.
                    while r.pos + 10 <= data_end {
                        let x = r.i16("hail x")? as f32 * 0.25;
                        let y = r.i16("hail y")? as f32 * 0.25;
                        let poh = r.i16("poh")?;
                        let posh = r.i16("posh")?;
                        let max_size = r.u16("hail size")?;
                        hail.push(Hail {
                            x_km: x,
                            y_km: y,
                            poh,
                            posh,
                            max_size,
                        });
                    }
                }
                20 => {
                    // Mesocyclone/MDA point features: [x, y, kind, attr] * n.
                    while r.pos + 8 <= data_end {
                        let x = r.i16("meso x")? as f32 * 0.25;
                        let y = r.i16("meso y")? as f32 * 0.25;
                        let kind = r.u16("meso kind")?;
                        let _attr = r.u16("meso attr")?;
                        meso.push(Meso {
                            x_km: x,
                            y_km: y,
                            kind: meso_kind(kind).to_string(),
                        });
                    }
                }
                23 => {
                    // SCIT past-position: a nested stream of (subcode u16, sublen u16, data)
                    // sub-packets; subcode 6 is a linked vector = one past-track polyline
                    // (i16 x/y pairs scaled by 0.25 km). Other sub-packets are skipped by length.
                    let mut sp = data_start;
                    while sp + 4 <= data_end {
                        let subcode = u16::from_be_bytes([msg[sp], msg[sp + 1]]);
                        let sublen = u16::from_be_bytes([msg[sp + 2], msg[sp + 3]]) as usize;
                        let sub_data = sp + 4;
                        let sub_end = (sub_data + sublen).min(data_end);
                        if subcode == 6 {
                            let mut poly = Vec::new();
                            let mut q = sub_data;
                            while q + 4 <= sub_end {
                                let x = i16::from_be_bytes([msg[q], msg[q + 1]]) as f32 * 0.25;
                                let y = i16::from_be_bytes([msg[q + 2], msg[q + 3]]) as f32 * 0.25;
                                poly.push((x, y));
                                q += 4;
                            }
                            if poly.len() >= 2 {
                                past_tracks.push(poly);
                            }
                        }
                        sp = sub_end.max(sp + 4);
                    }
                }
                _ => {}
            }
            // Advance to the next packet regardless of what we decoded.
            r.pos = data_end;
        }
        r.pos = layer_end;
    }
    Ok(())
}

/// Parse a Digital Radial Data Array (packet 16) body, cursor positioned just past the packet
/// code. Header: first_bin, nbins, i/j center, scale, nradials; per radial: nbytes, start*10,
/// delta*10, then `nbytes` level bytes.
fn parse_digital_radial(r: &mut Reader, layer_end: usize) -> Result<RadialArray> {
    let first_bin = r.u16("first_bin")?;
    let nbins = r.u16("nbins")?;
    let _i_center = r.i16("i_center")?;
    let _j_center = r.i16("j_center")?;
    let _scale = r.i16("scale")?;
    let nradials = r.u16("nradials")?;
    let mut radials = Vec::with_capacity(nradials as usize);
    for _ in 0..nradials {
        if r.pos + 6 > layer_end {
            break;
        }
        let nbytes = r.u16("radial nbytes")? as usize;
        let start_deg = r.i16("start angle")? as f32 * 0.1;
        let delta_deg = r.i16("angle delta")? as f32 * 0.1;
        let levels = r
            .take(nbytes.min(layer_end.saturating_sub(r.pos)), "radial data")?
            .to_vec();
        radials.push(Radial {
            start_deg,
            delta_deg,
            levels,
        });
    }
    Ok(RadialArray {
        first_bin,
        nbins,
        radials,
    })
}

/// Decode a 16-bit NEXRAD-ICD floating-point value (sign / 5-bit exponent, bias 16 / 10-bit
/// fraction), matching MetPy's `float16`. Used for DVL threshold scales/offsets.
pub fn icd_float16(val: u16) -> f32 {
    let frac = (val & 0x03ff) as f32;
    let exp = (val >> 10) & 0x1f;
    let sign = val >> 15;
    let value = if exp != 0 {
        2f32.powi(exp as i32 - 16) * (1.0 + frac / 1024.0)
    } else {
        frac / 512.0
    };
    if sign != 0 {
        -value
    } else {
        value
    }
}

/// Decode a Digital VIL (product 134) data level to kg/m², via the threshold table. Levels 0/1/255
/// are below-threshold / flagged / reserved → `None`. Linear below `log_start`, exponential above.
pub fn dvl_value(level: u8, thr: &[i16; 16]) -> Option<f32> {
    if level < 2 || level == 255 {
        return None;
    }
    let lin_scale = icd_float16(thr[0] as u16);
    let lin_offset = icd_float16(thr[1] as u16);
    let log_start = thr[2];
    let log_scale = icd_float16(thr[3] as u16);
    let log_offset = icd_float16(thr[4] as u16);
    // Thresholds come off the wire; a zero scale or a negative breakpoint (garbled product)
    // must not produce ±inf or a silently all-linear decode.
    if lin_scale == 0.0 || log_scale == 0.0 || log_start < 0 {
        return None;
    }
    let i = level as f32;
    if i16::from(level) < log_start {
        Some((i - lin_offset) / lin_scale)
    } else {
        Some(((i - log_offset) / log_scale).exp())
    }
}

/// Decode a Digital Base Reflectivity (N0B, product 153) data level to dBZ.
///
/// Unlike DVL, this product's thresholds are plain tenths — HW31 is the minimum value ×10 and
/// HW32 the increment ×10 (a live TLX product reads `[-320, 5, 254, …]`, i.e. −32 dBZ in 0.5 dB
/// steps). Levels 0 and 1 are below-threshold and range-folded.
pub fn n0b_value(level: u8, thr: &[i16; 16]) -> Option<f32> {
    if level < 2 {
        return None;
    }
    let min = thr[0] as f32 / 10.0;
    let inc = thr[1] as f32 / 10.0;
    if inc == 0.0 {
        return None;
    }
    Some(min + (level as f32 - 2.0) * inc)
}

/// Decode a Digital Base Velocity (N0G, product 154) data level to m/s.
///
/// Same tenths layout as N0B: HW31 is the minimum value ×10, HW32 the increment ×10 (a live TLX
/// product reads `[-635, 5, 254, …]`, i.e. −63.5 m/s in 0.5 m/s steps). Level 0 is below
/// threshold and level 1 is range-folded — both decode to `None`; a caller that colors
/// range-folding draws level 1 itself. Negative values are inbound (toward the radar).
pub fn n0g_value(level: u8, thr: &[i16; 16]) -> Option<f32> {
    n0b_value(level, thr)
}

/// Decode an Enhanced Echo Tops (product 135) data level to (kft, topped-flag), via the threshold
/// table. Levels 0/1 are below-threshold / flagged → `None`.
pub fn eet_value(level: u8, thr: &[i16; 16]) -> Option<(f32, bool)> {
    if level < 2 {
        return None;
    }
    let data_mask = thr[0] as u16;
    let scale = thr[1] as f32;
    let offset = thr[2] as f32;
    let topped_mask = thr[3] as u16;
    if scale == 0.0 {
        return None;
    }
    let kft = ((level as u16 & data_mask) as f32 - offset) / scale;
    let topped = (level as u16 & topped_mask) != 0;
    Some((kft, topped))
}

fn meso_kind(kind: u16) -> &'static str {
    match kind {
        1 => "Mesocyclone (ext.)",
        3 => "Mesocyclone",
        5 => "TVS (ext.)",
        6 => "ETVS (ext.)",
        7 => "TVS",
        8 => "ETVS",
        9 => "MDA",
        10 => "MDA (elev.)",
        11 => "MDA (weak)",
        _ => "Feature",
    }
}

/// Collect an alphanumeric block (`off..end`) as readable text (storm attribute / graphic table).
fn parse_text_block(msg: &[u8], off: usize, end: usize) -> Option<String> {
    let end = end.min(msg.len());
    if off + 10 > end {
        return None;
    }
    // The block is (num_chars, chars) line runs behind divider halfwords; extracting printable
    // ASCII runs reproduces the human-readable table without tracking every divider.
    let mut out = String::new();
    let mut run = 0;
    for &b in &msg[off..end] {
        if (0x20..0x7f).contains(&b) {
            out.push(b as char);
            run += 1;
        } else if run > 0 {
            out.push('\n');
            run = 0;
        }
    }
    let text: String = out
        .lines()
        .map(str::trim_end)
        .filter(|l| !l.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n");
    (!text.trim().is_empty()).then_some(text)
}

/// Strip the WMO abbreviated-heading text lines that precede the binary message.
fn strip_wmo(buf: &[u8]) -> &[u8] {
    let start = [b"SDUS".as_slice(), b"NXUS", b"NOUS"]
        .iter()
        .find_map(|sig| find(buf, sig))
        .unwrap_or(0);
    let mut pos = start;
    while let Some(nl) = find(&buf[pos..], b"\r\r\n") {
        let line = &buf[pos..pos + nl];
        let texty = nl < 80 && line.iter().all(|&c| c == b' ' || c.is_ascii_graphic());
        if !texty {
            break;
        }
        pos += nl + 3;
        // Stop when the payload (zlib marker or a binary/high byte) begins.
        match buf.get(pos) {
            Some(&c) if c == 0x78 || c < 0x20 => break,
            None => break,
            _ => {}
        }
    }
    &buf[pos..]
}

/// zlib-decompress `buf` (one or more concatenated frames); `None` if it isn't zlib.
fn zlib_all(buf: &[u8]) -> Option<Vec<u8>> {
    if buf.len() < 2 || buf[0] != 0x78 {
        return None;
    }
    let mut out = Vec::new();
    let mut cur = buf;
    while cur.len() >= 2 && cur[0] == 0x78 {
        let mut dec = flate2::read::ZlibDecoder::new(cur);
        let before = out.len();
        if dec.read_to_end(&mut out).is_err() {
            return (out.len() != before).then_some(out);
        }
        let consumed = dec.total_in() as usize;
        if consumed == 0 || consumed >= cur.len() {
            break;
        }
        cur = &cur[consumed..];
    }
    (!out.is_empty()).then_some(out)
}

/// BZIP2-decompress `buf` (the in-place compressed symbology block of high-res digital products).
fn bunzip(buf: &[u8]) -> Option<Vec<u8>> {
    let mut out = Vec::new();
    let mut dec = bzip2::read::BzDecoder::new(buf);
    match dec.read_to_end(&mut out) {
        _ if !out.is_empty() => Some(out),
        _ => None,
    }
}

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

/// A big-endian cursor over the decoded message.
struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(buf: &'a [u8]) -> Self {
        Self { buf, pos: 0 }
    }
    fn at(buf: &'a [u8], pos: usize) -> Self {
        Self { buf, pos }
    }
    fn take(&mut self, n: usize, what: &'static str) -> Result<&'a [u8]> {
        let end = self.pos + n;
        if end > self.buf.len() {
            return Err(Error::Short {
                what,
                need: n,
                have: self.buf.len().saturating_sub(self.pos),
            });
        }
        let s = &self.buf[self.pos..end];
        self.pos = end;
        Ok(s)
    }
    fn skip(&mut self, what: &'static str, n: usize) -> Result<()> {
        self.take(n, what).map(|_| ())
    }
    fn i16(&mut self, what: &'static str) -> Result<i16> {
        let b = self.take(2, what)?;
        Ok(i16::from_be_bytes([b[0], b[1]]))
    }
    fn u16(&mut self, what: &'static str) -> Result<u16> {
        let b = self.take(2, what)?;
        Ok(u16::from_be_bytes([b[0], b[1]]))
    }
    fn i32(&mut self, what: &'static str) -> Result<i32> {
        let b = self.take(4, what)?;
        Ok(i32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    }
    fn u32(&mut self, what: &'static str) -> Result<u32> {
        let b = self.take(4, what)?;
        Ok(u32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    }
    /// Read `n` bytes as trimmed printable ASCII.
    fn ascii(&mut self, n: usize) -> String {
        let end = (self.pos + n).min(self.buf.len());
        let s: String = self.buf[self.pos..end]
            .iter()
            .filter(|&&c| (0x20..0x7f).contains(&c))
            .map(|&c| c as char)
            .collect();
        self.pos = end;
        s.trim().to_string()
    }
}
